earl_short_main:
    resource: "@EarlShortMainBundle/Resources/config/routing.yml"
    prefix:   /

home:
    pattern:  /
    defaults: { _controller: EarlShortMainBundle:Default:index }

redirect:
    pattern: /{page}
    defaults: { _controller: EarlShortMainBundle:Redirect:index }
