earl_short_main:
    resource: "@EarlShortMainBundle/Resources/config/routing.yml"
    prefix:   /

#link:
#    pattern:  /link
#    defaults: { _controller: EarlShortMainBundle:Link }

#redirect:
#    pattern: /{page}
#    defaults: { _controller: EarlShortMainBundle:Redirect:index }
